import { AlertTriangle, Download, FlaskConical, Moon, Printer, ShieldCheck, Sun } from "lucide-react";
import { useState } from "react";
import DemoModeNotice from "./DemoModeNotice";


const STATUS_LABELS = {
  complete: "Complete",
  complete_with_limitations: "Complete with Limitations",
  incomplete: "Incomplete",
  failed: "Failed",
  superseded: "Superseded",
};


function formatDate(value) {
  if (!value) return "Not available";
  return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}


function sensitivityLabel(value) {
  if (value === true) return "Yes";
  if (value === false) return "No";
  return "Not sure";
}


function RoutineTimeline({ title, icon: Icon, steps }) {
  return <section className="report-section border-y border-slate-200 py-6"><div className="flex items-center gap-3"><Icon className="h-5 w-5 text-brand-700" aria-hidden="true" /><h2 className="text-xl font-bold text-slate-950">{title}</h2></div><ol className="mt-5 space-y-5">{steps.map((step) => <li key={`${title}-${step.step_number}`} className="grid grid-cols-[2rem_1fr] gap-4 break-inside-avoid"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-brand-600 text-sm font-bold text-white">{step.step_number}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-950">{step.product_name}</h3>{step.is_optional ? <span className="rounded-md bg-amber-100 px-2 py-1 text-xs font-bold text-amber-900">Optional</span> : null}{step.is_demo_product ? <span className="rounded-md bg-clinic-100 px-2 py-1 text-xs font-bold text-clinic-900">Demo</span> : null}</div><p className="mt-1 text-sm font-medium text-brand-700">{step.category} · {step.brand_name}</p><p className="mt-2 text-sm leading-6 text-slate-700">{step.purpose}</p><p className="mt-1 text-sm leading-6 text-slate-600">{step.usage_guidance}</p>{step.cautions.length ? <p className="mt-2 text-sm text-amber-900">Caution: {step.cautions.join(" ")}</p> : null}</div></li>)}</ol></section>;
}


export default function FinalReportView({ report, onExport, isExporting = false, printMode = false }) {
  const [privacyMode, setPrivacyMode] = useState("standard");
  const profile = report.skin_profile_summary || {};
  const skin = report.skin_type_summary || {};
  const concerns = report.visible_concern_summary || { observed: [], possible: [], uncertain: [] };
  return <article className="mx-auto max-w-7xl space-y-9" aria-labelledby="final-report-title">
    <DemoModeNotice visible={report.analysis_mode === "demonstration"} />
    <section className="report-section border-y border-slate-300 py-7"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-bold uppercase text-brand-700">DermaScan AI</p><h1 id="final-report-title" className="mt-2 text-3xl font-bold text-slate-950">{report.title}</h1><dl className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600"><div><dt className="inline font-semibold text-slate-800">Report ID: </dt><dd className="inline">{report.final_report_id}</dd></div><div><dt className="inline font-semibold text-slate-800">Version: </dt><dd className="inline">{report.report_version}</dd></div><div><dt className="inline font-semibold text-slate-800">Generated: </dt><dd className="inline">{formatDate(report.generated_at)}</dd></div></dl></div><div className="flex flex-col items-start gap-3"><span className="rounded-md bg-brand-100 px-3 py-2 text-sm font-bold text-brand-900">Status: {STATUS_LABELS[report.report_status] || report.report_status}</span>{!printMode ? <div className="print-hidden flex flex-wrap gap-2"><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-600"><Printer className="h-4 w-4" aria-hidden="true" />Print</button><label className="text-sm font-semibold text-slate-700"><span className="sr-only">PDF privacy mode</span><select value={privacyMode} onChange={(event) => setPrivacyMode(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 focus:outline-none focus:ring-2 focus:ring-brand-300"><option value="standard">Standard PDF</option><option value="privacy_reduced">Privacy-reduced PDF</option><option value="technical">Technical PDF</option></select></label><button type="button" onClick={() => onExport?.(privacyMode)} disabled={isExporting || !report.can_export_pdf} className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-300"><Download className="h-4 w-4" aria-hidden="true" />{isExporting ? "Exporting..." : "Export PDF"}</button></div> : null}</div></div></section>

    <section className="report-section border-l-4 border-red-500 bg-red-50 px-5 py-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-red-700" aria-hidden="true" /><div><h2 className="font-bold text-red-950">Important Disclaimer</h2><p className="mt-2 text-sm leading-6 text-red-950">{report.medical_disclaimer}</p><p className="mt-2 text-sm leading-6 text-red-950">Seek professional advice for severe, painful, infected, persistent, rapidly changing, or unusual skin concerns.</p></div></div></section>

    <section className="report-section"><h2 className="text-2xl font-bold text-slate-950">Executive Summary</h2><p className="mt-3 max-w-4xl text-base leading-7 text-slate-700">{report.summary}</p></section>

    <dl className="report-section grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div className="border-l-4 border-brand-500 px-4"><dt className="text-sm text-slate-600">Estimated skin type</dt><dd className="mt-1 text-xl font-bold text-slate-950">{skin.skin_type || "Unavailable"}</dd></div><div className="border-l-4 border-clinic-500 px-4"><dt className="text-sm text-slate-600">Skin-type confidence</dt><dd className="mt-1 text-xl font-bold text-slate-950">{skin.confidence_level || "Unavailable"}</dd></div><div className="border-l-4 border-leaf-500 px-4"><dt className="text-sm text-slate-600">Observed characteristics</dt><dd className="mt-1 text-xl font-bold text-slate-950">{concerns.observed.length}</dd></div><div className="border-l-4 border-amber-500 px-4"><dt className="text-sm text-slate-600">Recommendation confidence</dt><dd className="mt-1 text-xl font-bold text-slate-950">{report.engine_versions.recommendation ? "Recorded" : "Unavailable"}</dd></div><div className="border-l-4 border-slate-500 px-4"><dt className="text-sm text-slate-600">Routine steps</dt><dd className="mt-1 text-xl font-bold text-slate-950">{report.morning_routine.length + report.night_routine.length}</dd></div></dl>

    <section className="report-section border-y border-slate-200 py-6"><h2 className="text-xl font-bold text-slate-950">User-Provided Skin Profile</h2><p className="mt-1 text-sm text-slate-600">These values were self-reported and are separate from image observations.</p><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><dt className="font-semibold text-slate-800">Age group</dt><dd className="mt-1 text-slate-700">{profile.age_group || "Unavailable"}</dd></div><div><dt className="font-semibold text-slate-800">Country</dt><dd className="mt-1 text-slate-700">{profile.country || "Unavailable"}</dd></div><div><dt className="font-semibold text-slate-800">Oiliness / dryness</dt><dd className="mt-1 text-slate-700">{profile.oiliness_level || "Unavailable"} / {profile.dryness_level || "Unavailable"}</dd></div><div><dt className="font-semibold text-slate-800">Self-reported sensitivity</dt><dd className="mt-1 text-slate-700">{sensitivityLabel(profile.self_reported_sensitivity)}</dd></div><div><dt className="font-semibold text-slate-800">Fragrance preference</dt><dd className="mt-1 text-slate-700">{profile.fragrance_preference || "Unavailable"}</dd></div><div><dt className="font-semibold text-slate-800">Experience</dt><dd className="mt-1 text-slate-700">{profile.experience_level || "Unavailable"}</dd></div><div><dt className="font-semibold text-slate-800">Known allergies</dt><dd className="mt-1 text-slate-700">{profile.known_allergies?.join(", ") || "None reported"}</dd></div><div><dt className="font-semibold text-slate-800">Ingredients to avoid</dt><dd className="mt-1 text-slate-700">{profile.ingredients_to_avoid?.join(", ") || "None selected"}</dd></div></dl></section>

    <section className="report-section"><h2 className="text-xl font-bold text-slate-950">Safe Image Processing Summary</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4">{Object.entries(report.image_processing_summary || {}).map(([key, value]) => <div key={key} className="border-l-2 border-slate-300 pl-3"><dt className="font-semibold text-slate-800">{key.replaceAll("_", " ")}</dt><dd className="mt-1 text-slate-700">{typeof value === "boolean" ? (value ? "Yes" : "No") : value ?? "Unavailable"}</dd></div>)}</dl></section>

    <section className="report-section"><h2 className="text-xl font-bold text-slate-950">AI-Assisted Visible Results</h2><div className="mt-5 grid gap-6 lg:grid-cols-3">{["observed", "possible", "uncertain"].map((group) => <section key={group}><h3 className="font-semibold capitalize text-slate-950">{group}</h3>{concerns[group].length ? <ul className="mt-3 space-y-3">{concerns[group].map((item) => <li key={item.code} className="border-l-2 border-brand-300 pl-3 text-sm"><p className="font-semibold text-slate-900">{item.name}</p><p className="mt-1 text-slate-700">{item.visible_severity} visible appearance · {item.regions.join(", ") || "Full face"}</p><p className="mt-1 text-slate-600">Confidence: {item.confidence}%</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">None reported in this group.</p>}</section>)}</div></section>

    <section className="report-section grid gap-7 lg:grid-cols-2"><div><div className="flex items-center gap-2"><FlaskConical className="h-5 w-5 text-leaf-700" aria-hidden="true" /><h2 className="text-xl font-bold text-slate-950">Potentially Relevant Ingredient Roles</h2></div><ul className="mt-4 space-y-4">{report.ingredient_guidance.potentially_relevant.map((item) => <li key={item.ingredient_role} className="border-l-2 border-leaf-400 pl-3 text-sm"><p className="font-semibold text-slate-900">{item.ingredient_role}</p><p className="mt-1 text-slate-700">{item.reason}</p><p className="mt-1 text-slate-500">Examples: {item.examples.join(", ")}</p></li>)}</ul></div><div><h2 className="text-xl font-bold text-slate-950">Avoid or Review</h2><ul className="mt-4 space-y-4">{report.ingredient_guidance.avoid_or_review.length ? report.ingredient_guidance.avoid_or_review.map((item) => <li key={item.item} className="border-l-2 border-amber-400 pl-3 text-sm"><p className="font-semibold text-slate-900">{item.item}</p><p className="mt-1 text-slate-700">{item.reason}</p></li>) : <li className="text-sm text-slate-500">No selected avoidance item was available.</li>}</ul></div></section>

    <section className="report-section"><h2 className="text-2xl font-bold text-slate-950">Product Recommendations</h2><p className="mt-2 text-sm text-slate-600">Recommendation scores are project-specific relevance scores and do not guarantee product safety or effectiveness.</p><div className="mt-5 grid gap-5 lg:grid-cols-2">{report.product_recommendations.map((item) => <article key={item.product_id} className="break-inside-avoid rounded-lg border border-slate-200 bg-white p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase text-brand-700">{item.category} · Rank {item.rank}</p><h3 className="mt-1 text-lg font-bold text-slate-950">{item.product_name}</h3><p className="text-sm text-slate-600">{item.brand_name}</p></div><span className="h-fit rounded-md bg-brand-100 px-2 py-1 text-sm font-bold text-brand-900">{item.score}/100</span></div><p className="mt-4 text-sm leading-6 text-slate-700">{item.why_recommended}</p>{item.cautions.length ? <p className="mt-3 text-sm text-amber-900">Cautions: {item.cautions.join(" ")}</p> : null}<dl className="mt-4 grid grid-cols-2 gap-3 border-t border-slate-100 pt-3 text-xs text-slate-600"><div><dt className="font-semibold">Price at report time</dt><dd>{item.price_at_report_time ? `INR ${item.price_at_report_time.amount}` : "Unavailable"}</dd></div><div><dt className="font-semibold">Availability</dt><dd>{item.availability_at_report_time}</dd></div></dl>{item.demo_status ? <p className="mt-3 text-xs font-bold text-clinic-800">Demonstration Product</p> : null}</article>)}</div></section>

    <div className="grid gap-8 lg:grid-cols-2"><RoutineTimeline title="Morning Routine" icon={Sun} steps={report.morning_routine} /><RoutineTimeline title="Night Routine" icon={Moon} steps={report.night_routine} /></div>

    <section className="report-section grid gap-7 lg:grid-cols-2"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-leaf-700" aria-hidden="true" /><h2 className="text-xl font-bold text-slate-950">Safety Guidance</h2></div><ul className="mt-4 space-y-3">{report.safety_guidance.map((item) => <li key={item} className="text-sm leading-6 text-slate-700">{item}</li>)}</ul></div><div><h2 className="text-xl font-bold text-slate-950">Limitations</h2><ul className="mt-4 space-y-3">{report.limitations.map((item) => <li key={item} className="text-sm leading-6 text-slate-700">{item}</li>)}</ul></div></section>

    <details className="report-section border-y border-slate-200 py-5"><summary className="cursor-pointer font-semibold text-slate-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-600">Model, engine, and data-freshness details</summary><div className="mt-5 space-y-5 text-sm text-slate-700"><p><strong>Model versions:</strong> {JSON.stringify(report.model_versions)}</p><p><strong>Engine versions:</strong> {JSON.stringify(report.engine_versions)}</p><div className="overflow-x-auto"><table className="w-full border-collapse text-left"><caption className="sr-only">Product data freshness</caption><thead><tr className="border-b border-slate-300"><th className="p-2">Product ID</th><th className="p-2">Price checked</th><th className="p-2">Availability checked</th><th className="p-2">Source verified</th></tr></thead><tbody>{report.data_freshness.map((item) => <tr key={item.product_id} className="border-b border-slate-100"><td className="p-2">{item.product_id}</td><td className="p-2">{formatDate(item.price_checked_at)}</td><td className="p-2">{formatDate(item.availability_checked_at)}</td><td className="p-2">{formatDate(item.source_verified_at)}</td></tr>)}</tbody></table></div></div></details>
  </article>;
}
