COUNTRY_ALIASES = {
    "india": "IN",
    "in": "IN",
    "ind": "IN",
    "bharat": "IN",
    "united kingdom": "GB",
    "uk": "GB",
    "great britain": "GB",
    "united states": "US",
    "united states of america": "US",
    "usa": "US",
    "us": "US",
    "canada": "CA",
    "australia": "AU",
    "germany": "DE",
    "france": "FR",
    "singapore": "SG",
    "uae": "AE",
    "united arab emirates": "AE",
    "pakistan": "PK",
    "bangladesh": "BD",
    "nepal": "NP",
    "sri lanka": "LK",
    "global": "IN",
    "other": "IN",
    "worldwide": "IN",
}
